configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/untitled-ventures%2Fsetu-aa-sdk-6bd61572178c0a7076899dd3b68dd51245f2d2e0511f324fc6b69e55bbb13efe.yml
